services:
  - type: web
    name: guranda-api
    env: node
    rootDir: apps/api
    buildCommand: npm install && npm run build --prefix ../../packages/types && npx prisma generate && npm run build
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: SUPABASE_URL
        value: https://iibtgxsegeisfkfqmsgl.supabase.co
      - key: SUPABASE_PUBLISHABLE_KEY
        value: sb_publishable_NnJC48d0atOQcT826tfm8Q_AUzsnUUj
      - key: SUPABASE_SECRET_KEY
        sync: false
