import React, { useEffect, useState } from 'react';
import { View, Text, StyleSheet, TouchableOpacity, ScrollView, ActivityIndicator, Share, Platform } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { COLORS, TYPOGRAPHY, RADIUS, SPACING } from '../../theme';
import { fetchApi } from '../../utils/api';

// Auto-generated lease agreement rendered as a formal document.
// Shareable as plain text with both parties and the Guranda reference number.

export default function LeaseScreen({ navigation, route }: any) {
  const { tenancyId } = route.params || {};
  const [lease, setLease] = useState<any>(null);
  const [error, setError] = useState('');

  useEffect(() => {
    fetchApi(`/property/tenancy/${tenancyId}/lease`)
      .then(async res => {
        const d = await res.json();
        if (!res.ok) throw new Error(d.message || 'Could not load lease');
        setLease(d);
      })
      .catch(e => setError(e.message));
  }, [tenancyId]);

  const leaseText = lease
    ? `LEASE AGREEMENT ${lease.leaseNo}

Property: ${lease.property.title}
Address: ${lease.property.address}
Type: ${lease.property.kind}

Landlord / Agent: ${lease.landlord} (@${lease.landlordUsername})
Tenant: ${lease.tenant} (@${lease.tenantUsername})

Monthly rent: ${lease.rentAmount} MSH, payable via the Guranda wallet.
Lease start: ${new Date(lease.startDate).toDateString()}

Generated by Guranda Property on ${new Date(lease.generatedAt).toDateString()}.`
    : '';

  const shareLease = async () => {
    if (Platform.OS === 'web') {
      try {
        await (navigator as any).clipboard?.writeText(leaseText);
      } catch {}
      return;
    }
    Share.share({ message: leaseText });
  };

  return (
    <SafeAreaView style={styles.root} edges={['top']}>
      <View style={styles.header}>
        <TouchableOpacity style={styles.backBtn} onPress={() => navigation.goBack()}>
          <Ionicons name="arrow-back" size={22} color={COLORS.text} />
        </TouchableOpacity>
        <Text style={TYPOGRAPHY.h2}>Lease</Text>
        <TouchableOpacity style={styles.backBtn} onPress={shareLease}>
          <Ionicons name="share-outline" size={20} color={COLORS.text} />
        </TouchableOpacity>
      </View>

      {error !== '' && <Text style={styles.error}>{error}</Text>}
      {!lease && !error && <ActivityIndicator style={{ marginTop: 60 }} color="#2DD4BF" />}

      {lease && (
        <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: SPACING.lg, paddingBottom: 40 }}>
          <View style={styles.doc}>
            <Text style={styles.docSeal}>🏛️</Text>
            <Text style={styles.docTitle}>LEASE AGREEMENT</Text>
            <Text style={styles.docNo}>{lease.leaseNo}</Text>

            <View style={styles.divider} />

            <Text style={styles.clauseLabel}>THE PROPERTY</Text>
            <Text style={styles.clauseText}>{lease.property.title}</Text>
            <Text style={styles.clauseSub}>{lease.property.address} · {lease.property.kind}</Text>

            <Text style={styles.clauseLabel}>THE PARTIES</Text>
            <Text style={styles.clauseText}>Landlord / Agent: {lease.landlord}</Text>
            <Text style={styles.clauseSub}>@{lease.landlordUsername}</Text>
            <Text style={[styles.clauseText, { marginTop: 8 }]}>Tenant: {lease.tenant}</Text>
            <Text style={styles.clauseSub}>@{lease.tenantUsername}</Text>

            <Text style={styles.clauseLabel}>TERMS</Text>
            <Text style={styles.clauseText}>Monthly rent: {lease.rentAmount} MSH</Text>
            <Text style={styles.clauseSub}>Payable through the Guranda wallet. Each payment issues an automatic numbered receipt.</Text>
            <Text style={[styles.clauseText, { marginTop: 8 }]}>Lease start: {new Date(lease.startDate).toDateString()}</Text>
            <Text style={styles.clauseSub}>The lease runs month-to-month until ended by either party.</Text>

            <Text style={styles.clauseLabel}>MAINTENANCE</Text>
            <Text style={styles.clauseSub}>
              The tenant reports issues through Guranda Property. The agent tracks each
              issue from OPEN to RESOLVED.
            </Text>

            <View style={styles.divider} />
            <View style={styles.signRow}>
              <View style={styles.signBox}>
                <Text style={styles.signName}>{lease.landlord}</Text>
                <Text style={styles.signRole}>Landlord / Agent</Text>
              </View>
              <View style={styles.signBox}>
                <Text style={styles.signName}>{lease.tenant}</Text>
                <Text style={styles.signRole}>Tenant</Text>
              </View>
            </View>

            <Text style={styles.generated}>
              Generated by Guranda Property · {new Date(lease.generatedAt).toDateString()}
            </Text>
          </View>
        </ScrollView>
      )}
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#07211E' },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: SPACING.lg, paddingVertical: SPACING.md,
  },
  backBtn: {
    width: 40, height: 40, borderRadius: RADIUS.pill,
    backgroundColor: COLORS.glass, borderWidth: 1, borderColor: COLORS.glassBorder,
    justifyContent: 'center', alignItems: 'center',
  },
  error: { color: '#F87171', textAlign: 'center', marginTop: 40, paddingHorizontal: 24 },
  doc: {
    backgroundColor: '#F7F3E8',
    borderRadius: RADIUS.lg,
    padding: 22,
  },
  docSeal: { fontSize: 34, textAlign: 'center' },
  docTitle: { color: '#1F2933', fontSize: 18, fontWeight: '800', textAlign: 'center', letterSpacing: 2, marginTop: 6 },
  docNo: { color: '#6B7280', fontSize: 12, textAlign: 'center', marginTop: 3 },
  divider: { height: 1, backgroundColor: 'rgba(0,0,0,0.15)', marginVertical: 16 },
  clauseLabel: { color: '#0D9488', fontSize: 10.5, fontWeight: '800', letterSpacing: 1.5, marginTop: 14, marginBottom: 4 },
  clauseText: { color: '#1F2933', fontSize: 14.5, fontWeight: '700' },
  clauseSub: { color: '#4B5563', fontSize: 12.5, marginTop: 2, lineHeight: 18 },
  signRow: { flexDirection: 'row', gap: 14 },
  signBox: {
    flex: 1,
    borderTopWidth: 1.5, borderTopColor: '#1F2933',
    paddingTop: 6,
  },
  signName: { color: '#1F2933', fontSize: 12.5, fontWeight: '700' },
  signRole: { color: '#6B7280', fontSize: 10.5, marginTop: 1 },
  generated: { color: '#9CA3AF', fontSize: 10.5, textAlign: 'center', marginTop: 18 },
});
